// Utility functions for text processing, summarization, and translation
export const blogContent = `
      Artificial intelligence (AI), the ability of a digital computer or computer-controlled robot to perform tasks commonly associated with intelligent beings. The term is frequently applied to the project of developing systems endowed with the intellectual processes characteristic of humans, such as the ability to reason, discover meaning, generalize, or learn from past experience. Since their development in the 1940s, digital computers have been programmed to carry out very complex tasks—such as discovering proofs for mathematical theorems or playing chess—with great proficiency. Despite continuing advances in computer processing speed and memory capacity, there are as yet no programs that can match full human flexibility over wider domains or in tasks requiring much everyday knowledge. On the other hand, some programs have attained the performance levels of human experts and professionals in executing certain specific tasks, so that artificial intelligence in this limited sense is found in applications as diverse as medical diagnosis, computer search engines, voice or handwriting recognition, and chatbots. \n 
      What is intelligence?\n
      All but the simplest human behavior is ascribed to intelligence, while even the most complicated insect behavior is usually not taken as an indication of intelligence. What is the difference? Consider the behavior of the digger wasp, Sphex ichneumoneus. When the female wasp returns to her burrow with food, she first deposits it on the threshold, checks for intruders inside her burrow, and only then, if the coast is clear, carries her food inside. The real nature of the wasp’s instinctual behavior is revealed if the food is moved a few inches away from the entrance to her burrow while she is inside: on emerging, she will repeat the whole procedure as often as the food is displaced. Intelligence—conspicuously absent in the case of the wasp—must include the ability to adapt to new circumstances.`;


      export const blogSummary = "Artificial intelligence (AI) refers to the capability of a computer or robot to perform tasks that typically require human intelligence, such as reasoning, learning, and problem-solving. Since the 1940s, digital computers have been programmed to execute complex tasks like mathematical theorem proofs and chess playing.\n While AI has made significant advancements, it still lacks the full flexibility of human intelligence across various domains. However, AI applications have achieved expert-level performance in specific tasks such as medical diagnosis and voice recognition.";

export const urduTranslation ="مصنوعی ذہانت (AI) سے مراد کمپیوٹر یا روبوٹ کی ایسے کاموں کو انجام دینے کی صلاحیت ہے جن کے لیے عام طور پر انسانی ذہانت کی ضرورت ہوتی ہے، جیسے استدلال، سیکھنا، اور مسئلہ حل کرنا۔ 1940 کی دہائی سے، ڈیجیٹل کمپیوٹرز کو ریاضیاتی تھیوریم کے ثبوت اور شطرنج کے کھیل جیسے پیچیدہ کاموں کو انجام دینے کے لیے پروگرام بنایا گیا ہے۔ تاہم، AI ایپلی کیشنز نے طبی تشخیص اور آواز کی شناخت جیسے مخصوص کاموں میں ماہرانہ سطح کی کارکردگی حاصل کی ہے۔";

